version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12006:12006"
    env_file:
      - .env.production.local
    # Use the proper entrypoint from the Dockerfile
    # and override with the command to run the server with SSE transport
    command: ["--transport", "sse", "--port", "12006"]
    healthcheck:
      test: ["CMD", "curl", "-f", "--head", "--max-time", "5", "http://127.0.0.1:12006/sse"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
